version: "3.9"

services:

    database:
        image: postgres
        container_name: 'account-service-postgres'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=account
            - POSTGRES_PASSWORD=account
            - POSTGRES_DB=account-service
        volumes:
            - ./.docker/postgres:/var/lib/postgresql
            - ./scripts/database:/docker-entrypoint-initdb.d/
        networks:
            - default